import { test } from "@playwright/test"

// Generated by `redspec new journeys access` from the flows in spec.ts — one
// per reachable path. Regenerate rather than edit. Each stays fixme until the
// slice that claims its JOURNEY- lands and un-fixmes it.
