import { test } from "@playwright/test"

// Generated by `redspec new journeys access` from the flows in spec.ts — one
// per reachable path. Regenerate rather than edit. Each stays fixme until the
// slice that claims its JOURNEY- lands and un-fixmes it.

test.fixme("JOURNEY-access-first-account [path 1]: An account of their own, and a shell that names the address it belongs to.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Types the address they read email at
  // STATE-access-door-filled
  //   → Presses Continue
  // STATE-access-door-sending
  //   → Clerk sends the code and the screen changes
  // STATE-access-code-empty
  //   → Types the six digits from the email
  // STATE-access-code-filled
  //   → Presses Continue
  // STATE-access-code-verifying
  //   → Clerk accepts the code, then transfers the verified attempt into a new account
  // STATE-access-code-verified
  //   → The app takes over
  // STATE-access-app-signed-in
  // Ends: An account of their own, and a shell that names the address it belongs to.
  await page.goto("/")
})

test.fixme("JOURNEY-access-first-account [path 2]: An account of their own, and a shell that names the address it belongs to.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Types the address they read email at
  // STATE-access-door-filled
  //   → Presses Continue
  // STATE-access-door-sending
  //   → Clerk sends the code and the screen changes
  // STATE-access-code-empty
  //   → Three of the six digits are in
  // STATE-access-code-partial
  // STATE-access-code-filled
  //   → Presses Continue
  // STATE-access-code-verifying
  //   → Clerk accepts the code, then transfers the verified attempt into a new account
  // STATE-access-code-verified
  //   → The app takes over
  // STATE-access-app-signed-in
  // Ends: An account of their own, and a shell that names the address it belongs to.
  await page.goto("/")
})

test.fixme("JOURNEY-access-first-account [path 3]: An account of their own, and a shell that names the address it belongs to.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Types the address they read email at
  // STATE-access-door-filled
  //   → Presses Continue
  // STATE-access-door-sending
  //   → Clerk sends the code and the screen changes
  // STATE-access-code-empty
  //   → The address the code went to runs to 250 characters
  // STATE-access-code-long-email
  // STATE-access-code-filled
  //   → Presses Continue
  // STATE-access-code-verifying
  //   → Clerk accepts the code, then transfers the verified attempt into a new account
  // STATE-access-code-verified
  //   → The app takes over
  // STATE-access-app-signed-in
  // Ends: An account of their own, and a shell that names the address it belongs to.
  await page.goto("/")
})

test.fixme("JOURNEY-access-first-account [path 4]: An account of their own, and a shell that names the address it belongs to.", async ({ page }) => {
  // STATE-access-door-empty
  //   → The address runs to 250 characters
  // STATE-access-door-long-email
  // STATE-access-door-filled
  //   → Presses Continue
  // STATE-access-door-sending
  //   → Clerk sends the code and the screen changes
  // STATE-access-code-empty
  //   → Types the six digits from the email
  // STATE-access-code-filled
  //   → Presses Continue
  // STATE-access-code-verifying
  //   → Clerk accepts the code, then transfers the verified attempt into a new account
  // STATE-access-code-verified
  //   → The app takes over
  // STATE-access-app-signed-in
  // Ends: An account of their own, and a shell that names the address it belongs to.
  await page.goto("/")
})

test.fixme("JOURNEY-access-first-account [path 5]: An account of their own, and a shell that names the address it belongs to.", async ({ page }) => {
  // STATE-access-door-empty
  //   → The address runs to 250 characters
  // STATE-access-door-long-email
  // STATE-access-door-filled
  //   → Presses Continue
  // STATE-access-door-sending
  //   → Clerk sends the code and the screen changes
  // STATE-access-code-empty
  //   → Three of the six digits are in
  // STATE-access-code-partial
  // STATE-access-code-filled
  //   → Presses Continue
  // STATE-access-code-verifying
  //   → Clerk accepts the code, then transfers the verified attempt into a new account
  // STATE-access-code-verified
  //   → The app takes over
  // STATE-access-app-signed-in
  // Ends: An account of their own, and a shell that names the address it belongs to.
  await page.goto("/")
})

test.fixme("JOURNEY-access-first-account [path 6]: An account of their own, and a shell that names the address it belongs to.", async ({ page }) => {
  // STATE-access-door-empty
  //   → The address runs to 250 characters
  // STATE-access-door-long-email
  // STATE-access-door-filled
  //   → Presses Continue
  // STATE-access-door-sending
  //   → Clerk sends the code and the screen changes
  // STATE-access-code-empty
  //   → The address the code went to runs to 250 characters
  // STATE-access-code-long-email
  // STATE-access-code-filled
  //   → Presses Continue
  // STATE-access-code-verifying
  //   → Clerk accepts the code, then transfers the verified attempt into a new account
  // STATE-access-code-verified
  //   → The app takes over
  // STATE-access-app-signed-in
  // Ends: An account of their own, and a shell that names the address it belongs to.
  await page.goto("/")
})

test.fixme("JOURNEY-access-first-account [path 7]: No way in, and a screen that makes clear it is us and not them, so they try again later rather than doubting their own address.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Clerk cannot be reached at all
  // STATE-access-door-unavailable
  // Ends: No way in, and a screen that makes clear it is us and not them, so they try again later rather than doubting their own address.
  await page.goto("/")
})

test.fixme("JOURNEY-access-with-google [path 1]: An account of their own, and a shell that names the Google address it belongs to.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Presses Continue with Google
  // STATE-access-door-sending
  //   → The browser leaves for Google, they consent, and Google sends them back
  // STATE-access-callback-working
  //   → Clerk links the account and finalizes the session
  // STATE-access-app-signed-in
  // Ends: An account of their own, and a shell that names the Google address it belongs to.
  await page.goto("/")
})

test.fixme("JOURNEY-access-with-google [path 2]: An account of their own, and a shell that names the Google address it belongs to.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Presses Continue with Google
  // STATE-access-door-sending
  //   → The browser leaves for Google, they consent, and Google sends them back
  // STATE-access-callback-working
  //   → Google returns an address it has not verified and an account already holds it, so Clerk sends a code before it will link them
  // STATE-access-code-empty
  // STATE-access-app-signed-in
  // Ends: An account of their own, and a shell that names the Google address it belongs to.
  await page.goto("/")
})

test.fixme("JOURNEY-access-with-google [path 3]: Told this address cannot be used here and given a person to ask about it, rather than being sent round the Google loop again to the same answer.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Presses Continue with Google
  // STATE-access-door-sending
  //   → The browser leaves for Google, they consent, and Google sends them back
  // STATE-access-callback-working
  //   → The Google address is one this instance refuses
  // STATE-access-callback-blocked
  // Ends: Told this address cannot be used here and given a person to ask about it, rather than being sent round the Google loop again to the same answer.
  await page.goto("/")
})

test.fixme("JOURNEY-access-return [path 1]: Back in, with everything as they left it and nothing new to remember.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Types the address the account is under
  // STATE-access-door-filled
  //   → Presses Continue
  // STATE-access-door-sending
  //   → Clerk sends the code and the screen changes
  // STATE-access-code-empty
  //   → Types the six digits from the email
  // STATE-access-code-filled
  //   → Presses Continue
  // STATE-access-code-verifying
  //   → Clerk accepts the code and revives the session
  // STATE-access-code-verified
  //   → The app takes over
  // STATE-access-app-signed-in
  // Ends: Back in, with everything as they left it and nothing new to remember.
  await page.goto("/")
})

test.fixme("JOURNEY-access-return [path 2]: Back in, with everything as they left it and nothing new to remember.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Types the address the account is under
  // STATE-access-door-filled
  //   → Presses Continue
  // STATE-access-door-sending
  //   → Clerk sends the code and the screen changes
  // STATE-access-code-empty
  //   → They finish signing in in another tab while this screen waits
  // STATE-access-code-already-signed-in
  // STATE-access-app-signed-in
  // Ends: Back in, with everything as they left it and nothing new to remember.
  await page.goto("/")
})

test.fixme("JOURNEY-access-return [path 3]: Told this address cannot be used here and given a person to ask about it -- never told whether an account exists behind it, which is the one thing this screen must not say.", async ({ page }) => {
  // STATE-access-door-empty
  //   → Types the address the account is under
  // STATE-access-door-filled
  //   → The address is one this instance refuses -- which says nothing about whether an account exists
  // STATE-access-door-blocked
  // Ends: Told this address cannot be used here and given a person to ask about it -- never told whether an account exists behind it, which is the one thing this screen must not say.
  await page.goto("/")
})

test.fixme("JOURNEY-access-return [path 4]: Back in, with everything as they left it and nothing new to remember.", async ({ page }) => {
  // STATE-access-door-empty
  //   → They are already signed in in another tab
  // STATE-access-door-already-signed-in
  // STATE-access-app-signed-in
  // Ends: Back in, with everything as they left it and nothing new to remember.
  await page.goto("/")
})

test.fixme("JOURNEY-access-sign-out [path 1]: Out, told so in as many words, and looking at the way back in.", async ({ page }) => {
  // STATE-access-app-signed-in
  //   → Presses Sign out
  // STATE-access-app-signing-out
  //   → Clerk ends the session
  // STATE-access-door-signed-out
  // Ends: Out, told so in as many words, and looking at the way back in.
  await page.goto("/")
})

test.fixme("JOURNEY-access-sign-out [path 2]: Out, told so in as many words, and looking at the way back in.", async ({ page }) => {
  // STATE-access-app-signed-in
  //   → The session was ended elsewhere and this tab has not noticed for up to a minute
  // STATE-access-app-session-ended
  // STATE-access-door-signed-out
  // Ends: Out, told so in as many words, and looking at the way back in.
  await page.goto("/")
})
